export const spotify = {
  bands: {
    top: [
      'New Candys',
      'Magic Shoppe',
      'The Black Angels',
      'Tess Parks & Anton Newcombe',
      'The KVB',
      'David Bowie',
      'Tess Parks',
      'Black Rebel Motorcycle Club',
      'The Brian Jonestown Massacre',
      'Preoccupations',
      'Sonic Jesus',
      'Psychic Ills',
      'Wooden Shjips',
      'The Babies',
      'Night Beats',
      'Tame Impala',
      'The Underground Youth',
      'Singapore Sling',
      'Motorama',
      'Thee Oh Sees',
      'Moon Duo',
      'Iggy Pop',
      'Parquet Courts',
      'Desert Mountain Tribe',
      'Frightened Rabbit',
      'The Rolling Stones',
      'The Blue Angel Lounge',
      'A Place To Bury Strangers',
      'The Von Bondies',
      'The Smiths',
      'Fuzz',
      '10 000 Russos',
      'Soviet Soviet',
      'First Breath After Coma',
      'Billy Idol',
      'Indian Askin',
      'Whispering Sons',
      'The Stooges',
      'The Cramps',
      'Bob Dylan',
      'Viv and the Sect',
      'Metronomy',
      'Johnossi',
      'Slowdive',
      'TOY',
      'Fleetwood Mac',
      'Ty Segall',
      'Holy Wave',
      'Kasabian',
      'Dirty Pretty Things',
    ],
    similar: [
      'Black Market Karma',
      'The Third Sound',
      'The Party Favors',
      'The Spyrals',
      'Tales of Murder and Dust',
      'Girless and the Orphan',
      'Rancho Relaxo',
      'Bad Liquor Pond',
      'Dead Rabbits',
      'The Lucid Dream',
      'Chicos de Nazca',
      'Medicine Boy',
      'Herself',
      'Non voglio che Clara',
      'Jocelyn Pulsar',
      'Chewingum',
      'Kingdom of the Holy Sun',
      'The Orange Revival',
      'Jesus on Heroine',
      'Sisters of Your Sunshine Vapor',
      'Hurricane Heart Attacks',
      'Telstar Sound Drone',
      'Pete International Airport',
      'The Volta Sound',
      'La Hell Gang',
      'House Of Fire',
      'Flavor Crystals',
      'The Warlocks',
      'Dead Meadow',
      'Sleepy Sun',
      'Black Mountain',
      'The Dolly Rocker Movement',
      'Spindrift',
      'Goat',
      'The Asteroid #4',
      'Assemble Head In Sunburst Sound',
      'Radio Moscow',
      'All Them Witches',
      'Joel Gion',
      'MIEN',
      'Matt Hollywood & the Bad Feelings',
      'Ulrika Spacek',
      'The Limiñanas',
      'Soft Kill',
      'Led Er Est',
      'Velvet Condom',
      'Xeno & Oaklander',
      'Skeleton Hands',
      'This Cold Night',
      'Tropic of Cancer',
      'Lebanon Hanover',
      'Tempers',
      'All Your Sisters',
      'Agent Side Grinder',
      'Black Marble',
      'Bleib Modern',
      'Drab Majesty',
      'Ash Code',
      'Light Asylum',
      'The Soft Moon',
      'Ritual Howls',
      'Human Tetris',
      'Lou Reed',
      'T. Rex',
      'Roxy Music',
      'Talking Heads',
      'Queen',
      'Brian Eno',
      'TheVelvet Underground',
      'The Kinks',
      'Joy Division',
      'Blondie',
      'Pretenders',
      'Echo & the Bunnymen',
      'The Clash',
      'The Stranglers',
      'New Order',
      'Pulp',
      'George Harrison',
      'Patti Smith',
      'The Who',
      'The Black Ryder',
      'The Stevenson Ranch Davidians',
      'Dead Skeletons',
      'The Dandy Warhols',
      'The Vines',
      'The Dead Weather',
      'The Raconteurs',
      'The Kills',
      'Band Of Skulls',
      'Eagles Of Death Metal',
      'The Hives',
      'Death From Above 1979',
      'Blood Red Shoes',
      'The Raveonettes',
      'Primal Scream',
      'Them Crooked Vultures',
      'Dan Auerbach',
      'Doves',
      'Supergrass',
      'Wolfmother',
      'Spiritualized',
      'The Jesus and Mary Chain',
      'Galaxie 500',
      'Ought',
      'The Men',
      'Shame',
      'Girl Band',
      'IDLES',
      'Iceage',
      'Flasher',
      'Priests',
      'Savages',
      'Protomartyr',
      'B Boys',
      'HMLTD',
      'Omni',
      'Exploded View',
      'FRIGS',
      'Mourn',
      'A. Savage',
      'Big Ups',
      'Drahla',
      'Holograms',
      'Dead Vibrations',
      'The Oscillation',
      'Spirit Valley',
      'The Gluts',
      'Throw Down Bones',
      'CULT OF DOM KELLER',
      'Lumerians',
      'Darker My Love',
      'Bardo Pond',
      'White Hills',
      'Dungen',
      'The Myrrors',
      'Harlem',
      'Tijuana Panthers',
      'The Beets',
      'Sonny & The Sunsets',
      'Bleached',
      'Jacuzzi Boys',
      'Cloud Nothings',
      'Dead Ghosts',
      'Bass Drum of Death',
      'Vivian Girls',
      'The Almighty Defenders',
      'Nobunny',
      'Natural Child',
      'White Fence',
      'Smith Westerns',
      'Shannon and The Clams',
      'The Fresh & Onlys',
      'Hunx & His Punx',
      'Woods',
      'Black Lips',
      'Meatbodies',
      'King Tuff',
      'Guantanamo Baywatch',
      'Cool Ghouls',
      'Mystic Braves',
      'Ty Segall Band',
      'Acid Baby Jesus',
      'Unknown Mortal Orchestra',
      'Pond',
      'Real Estate',
      'Beach Fossils',
      'Deerhunter',
      'Grizzly Bear',
      'Toro y Moi',
      'Neon Indian',
      'Washed Out',
      'Foxygen',
      'DIIV',
      "Melody's Echo Chamber",
      'The Drums',
      'Beach House',
      'Ariel Pink',
      'King Krule',
      'Wild Nothing',
      'Mac DeMarco',
      'The Growlers',
      'Mild High Club',
      'The Koolaid Electric Company',
      'The Morning After Girls',
      'The Lovetones',
      'The Telescopes',
      'Pompeya',
      'The Horrors',
      'Буерак',
      'Utro',
      'Ploho',
      'Hawaiian Gremlins',
      'She Past Away',
      'Super Besse',
      'Los Blenders',
      'Thieves Like Us',
      'BRANDENBURG',
      'Sad Lovers & Giants',
      'Young Tender',
      'OCS',
      'Jay Reatard',
      'The King Khan & BBQ Show',
      'Gøggs',
      'Coachwhips',
      'JEFF The Brotherhood',
      'Föllakzoid',
      'Crocodiles',
      'Crystal Stilts',
      'New York Dolls',
      'Television',
      'Buzzcocks',
      'The Modern Lovers',
      'Sex Pistols',
      'The Damned',
      'MC5',
      'Richard Hell',
      'Public Image Ltd.',
      'Johnny Thunders',
      'X',
      'Ramones',
      'Amen Dunes',
      'Speedy Ortiz',
      'No Age',
      'Stephen Malkmus & The Jicks',
      'Kurt Vile',
      'Cut Worms',
      'White Denim',
      'Minami Deutsch',
      'Mastersystem',
      'We Were Promised Jetpacks',
      'Owl John',
      'The Twilight Sad',
      'Admiral Fallow',
      'The National',
      'Idlewild',
      'Los Campesinos!',
      'Okkervil River',
      'The XCERTS',
      'The Decemberists',
      'Twin Atlantic',
      'Augustines',
      'The Weakerthans',
      'Wolf Parade',
      'Japandroids',
      'King Creosote',
      'The Antlers',
      'The Hold Steady',
      'The Mountain Goats',
      'The Animals',
      'Jimi Hendrix',
      'Cream',
      'Faces',
      'The Yardbirds',
      'The Doors',
      'Steppenwolf',
      'Chuck Berry',
      'Derek & The Dominos',
      'Creedence Clearwater Revival',
      'Steve Miller Band',
      'Canned Heat',
      'The Band',
      'Janis Joplin',
      'John Lennon',
      'Led Zeppelin',
      'The Allman Brothers Band',
      'The Quarter After',
      'Ringo Deathstarr',
      'Autolux',
      'My Bloody Valentine',
      'True Widow',
      'Airiel',
      'No Joy',
      'Cold Cave',
      'Ride',
      'Swervedriver',
      'Film School',
      'Liars',
      'Suuns',
      'Louis XIV',
      'The Greenhornes',
      '22-20s',
      'The Duke Spirit',
      'The Datsuns',
      'The Mooney Suzuki',
      'The Subways',
      'The Detroit Cobras',
      'Nine Black Alps',
      'Morrissey',
      'The Psychedelic Furs',
      'The Cure',
      'The The',
      'Happy Mondays',
      'The Stone Roses',
      'The Jam',
      'Blur',
      'Bauhaus',
      'Siouxsie and the Banshees',
      'The Libertines',
      'Cocteau Twins',
      'James',
      'Pixies',
      'Wand',
      'The Murlocs',
      'Frankie and the Witch Fingers',
      'Kikagaku Moyo',
      'Froth',
      'levitation room',
      'Mt. Mountain',
      'Pretty Lightning',
      'Sundays & Cybele',
      'Stone Dead',
      'The Lemon Lovers',
      'Las Cobras',
      'Flowers Must Die',
      'Anthroprophh',
      'Has A Shadow',
      'RMFTM',
      'Radar Men from the Moon',
      'Dead Sea Apes',
      'Holygram',
      'The Agnes Circle',
      'Воллны',
      'Second Still',
      'Geometric Vision',
      "You Can't Win, CharlieBrown",
      'Surma',
      'Noiserv',
      'Best Youth',
      'Linda Martini',
      'The Legendary Tigerman',
      'B Fachada',
      'Samuel Uria',
      'Bruno Pernadas',
      'Ornatos Violeta',
      'Capitão Fausto',
      'Dead Combo',
      'Paus',
      'Diabo Na Cruz',
      'X-Wife',
      'Foge Foge Bandido',
      'Sensible Soccers',
      'peixe : avião',
      'Nice Weather for Ducks',
      'Orelha Negra',
      'The Cars',
      'Duran Duran',
      'The Romantics',
      'Men At Work',
      'Robert Palmer',
      'The Fixx',
      'Howard Jones',
      'Cheap Trick',
      'Wang Chung',
      'Thompson Twins',
      'Pat Benatar',
      'INXS',
      'Simple Minds',
      'Fine Young Cannibals',
      'Loverboy',
      'The Human League',
      'A Flock Of Seagulls',
      'The Cult',
      'ABC',
      'Billy Squier',
      'Sue the Night',
      'Canshaker Pi',
      'Bombay',
      'EUT',
      'Lucas Hamming',
      'The Mysterons',
      'Drive Like Maria',
      'Dawn Brothers',
      'Mozes and the Firstborn',
      'Iguana Death Cult',
      'Birth Of Joy',
      'Paceshifters',
      'DeWolff',
      'De Staat',
      'Blaudzun',
      'The Homesick',
      'JOHAN',
      'Moss',
      'Scram C Baby',
      'Lewsberg',
      'SUPERNOVA 1006',
      'Sextile',
      'Box And The Twins',
      'Night Sins',
      'A Projection',
      'Veil of Light',
      'Buzz Kull',
      'Hante.',
      'Death Of Lovers',
      'The Gun Club',
      'Dead Boys',
      'Hüsker Dü',
      'Wire',
      'The Saints',
      'Johnny Thunders & The Heartbreakers',
      'Minutemen',
      'Gang Of Four',
      'The Fall',
      'The Reverend Horton Heat',
      'The Meteors',
      'Batmobile',
      'Demented Are Go',
      'Nekromantix',
      'Koffin Kats',
      'Link Wray',
      'Horrorpops',
      'Tiger Army',
      'The Sonics',
      'Dead Moon',
      'The Hillbilly Moon Explosion',
      'Van Morrison',
      'Crosby, Stills, Nash & Young',
      'Leonard Cohen',
      'Paul Simon',
      'Neil Young',
      'Crosby, Stills & Nash',
      'Donovan',
      'Warren Zevon',
      'The Byrds',
      'Nick Drake',
      'Joni Mitchell',
      'Traveling Wilburys',
      'Townes Van Zandt',
      'Yusuf / CatStevens',
      'Joan Baez',
      'Tom Waits',
      'The Risin Sun',
      'Nelson y Los Filisteos',
      'Cascabel',
      'San Pedro el Cortez',
      'The Cavernarios',
      'Build a Vista',
      'Los Explosivos',
      'TELEKRIMEN',
      'The Broccolis',
      'Os Haxixins',
      'Sgt. Papers',
      'The Gruesomes',
      'Moon Moon',
      'The Mud Howlers',
      'Wau Y Los Arrrghs!!',
      'The Barbacans',
      'Wild Evel And The Trashbones',
      'Los Magnificos',
      'The Bomboras',
      'The Cynics',
      'Friendly Fires',
      'The Rapture',
      'Hot Chip',
      'Klaxons',
      'Cut Copy',
      'The Whitest Boy Alive',
      'WhoMadeWho',
      'Crystal Castles',
      'Digitalism',
      '!!!',
      'Miami Horror',
      'Foals',
      'Hercules & Love Affair',
      'Sébastien Tellier',
      'LCD Soundsystem',
      'Wild Beasts',
      'Simian Mobile Disco',
      'Fujiya & Miyagi',
      'Caribou',
      'Timo Räisänen',
      'Moneybrother',
      'Markus Krunegård',
      'Caesars',
      'Broder Daniel',
      'The Ark',
      'Mando Diao',
      'kent',
      'Deportees',
      'Familjen',
      'Håkan Hellström',
      'bob hund',
      'Melody Club',
      'Laakso',
      'HOFFMAESTRO',
      'Hästpojken',
      'Teddybears',
      'Sahara Hotnights',
      'Säkert!',
      'The Soundtrack Of Our Lives',
      'Pale Saints',
      'Lush',
      'Chapterhouse',
      'Mojave 3',
      'LSD and the Search for God',
      'Drop Nineteens',
      'Catherine Wheel',
      'Swirlies',
      'Red House Painters',
      'Hope Sandoval and the Warm Inventions',
      'FEWS',
      'Jacco Gardner',
      'Morgan Delt',
      'S.C.U.M',
      'Splashh',
      'The Wytches',
      'The Moonlandingz',
      'Girls Names',
      'Temples',
      'Steely Dan',
      'The Doobie Brothers',
      'Tom Petty and the Heartbreakers',
      'Don Henley',
      'Eagles',
      'America',
      'Peter Frampton',
      'Steve Winwood',
      'Heart',
      'John Mellencamp',
      'Jackson Browne',
      'Daryl Hall & John Oates',
      'Joe Walsh',
      'Billy Joel',
      'Damaged Bug',
      'L.A. WITCH',
      'Sugar Candy Mountain',
      'Mr. Elevator & The Brain Hotel',
      'Gap Dream',
      'Kaiser Chiefs',
      'Razorlight',
      'The Enemy',
      'Hard-FI',
      'The Last Shadow Puppets',
      'Franz Ferdinand',
      'The Pigeon Detectives',
      'The Fratellis',
      'Babyshambles',
      'The View',
      'The Coral',
      'White Lies',
      'Miles Kane',
      "Noel Gallagher's High Flying Birds",
      'Courteeners',
      'Maximo Park',
      'Editors',
      'The Holloways',
      'The Rifles',
      'Little Man Tate',
      'Peter Doherty',
      'The Rakes',
      'Milburn',
      'The Cribs',
      'The Zutons',
      'Carl Barât',
    ],
  },
  name: 'spotify_gereeet',
  __v: 1,
};
export const lastfm = {
  bands: {
    top: [
      'New Candys',
      'Tess Parks',
      'Magic Shoppe',
      'The Black Angels',
      'The KVB',
      'Sonic Jesus',
      'The Rolling Stones',
      'Preoccupations',
      'Tame Impala',
      'David Bowie',
      'Night Beats',
      'The Babies',
      'Psychic Ills',
      'The Brian Jonestown Massacre',
      'Thee Oh Sees',
      'The Underground Youth',
      'Wooden Shjips',
      'Singapore Sling',
      'A Place to Bury Strangers',
      'The Blue Angel Lounge',
      '10 000 Russos',
      'Desert Mountain Tribe',
      'Moon Duo',
      'Holy Wave',
      'Fuzz',
      'Black Rebel Motorcycle Club',
      'First Breath After Coma',
      'Parquet Courts',
      'Whispering Sons',
      'Ulrika Spacek',
      'Metronomy',
      'The Von Bondies',
      'Miles Kane',
      'The Smiths',
      'Indian Askin',
      'Ty Segall',
      'Slowdive',
      'Soviet Soviet',
      'The Limiñanas',
      'Viv and The Sect',
      'Mystic Braves',
      'Bob Dylan',
      'The Last Shadow Puppets',
      'The Warlocks',
      'Allah-Las',
      'Johnossi',
      'Josefin Öhrn + The Liberation',
      'Kasabian',
      'The Dolly Rocker Movement',
      'Bass Drum of Death',
    ],
    similar: [
      'The Asteroid #4',
      'The Cult of Dom Keller',
      'Bad Liquor Pond',
      'Vibravoid',
      'Secret Colours',
      'Heaters',
      'The Citradels',
      'Dead Skeletons',
      'Christian Bland & The Revelators',
      'Black Market Karma',
      'The Oscillation',
      'White Manna',
      'Weird Owl',
      'tess parks & anton newcombe',
      'Dead Meadow',
      'Wall of Death',
      'Elephant Stone',
      'Sugar Candy Mountain',
      'Sleepy Sun',
      'The Dandy Warhols',
      'Cat Power',
      'The Babe Rainbow',
      'Courtney Barnett',
      'Diane Coffee',
      'The Stevenson Ranch Davidians',
      'Kurt Vile',
      'Toy',
      'Rancho Relaxo',
      'Telstar Sound Drone',
      'The Orange Revival',
      'The Spyrals',
      'Jesus On Heroine',
      'Kingdom of the Holy Sun',
      'Sisters of Your Sunshine Vapor',
      'La Hell Gang',
      'The Confederate Dead',
      'Sir Robin & The Longbowmen',
      'The Janitors',
      'My Expansive Awareness',
      'Flavor Crystals',
      'DEAD HORSE ONE',
      'Ride Into the Sun',
      'Holy Monitor',
      'Pretty Lightning',
      'Joel Gion',
      'Buried Feather',
      'House Of Fire',
      'You Said Strange',
      'the valkarys',
      'Helicon',
      'Black Mountain',
      'Radio Moscow',
      'The Flying Eyes',
      'Goat',
      'Wolf People',
      'All Them Witches',
      'Temples',
      'Causa Sui',
      'Pond',
      'Screen Vinyl Image',
      'Tropic of Cancer',
      'The Soft Moon',
      'Cold Showers',
      'Soft Kill',
      'Tempers',
      'Ritual Howls',
      'Ash Code',
      'Bleib Modern',
      'She Past Away',
      'Cold Cave',
      'M!R!M',
      'Lebanon Hanover',
      'Black Marble',
      'Buzz Kull',
      'DRAB MAJESTY',
      'Agent Side Grinder',
      'HTRK',
      'Human Tetris',
      'Veil Of Light',
      'Ssleeping desiresS',
      'This Cold Night',
      'Dead Vibrations',
      'The Stargazer Lilies',
      'The Lucid Dream',
      'The Vacant Lots',
      'Spirit Valley',
      'Tales of Murder and Dust',
      'Lorelle Meets The Obsolete',
      'The Gluts',
      'The Myrrors',
      'Lumerians',
      'Spacemen 3',
      'The Who',
      'Keith Richards',
      'Mick Jagger',
      'The Beatles',
      'The Kinks',
      'Led Zeppelin',
      'The Doors',
      'John Lennon',
      'Jimi Hendrix',
      'Creedence Clearwater Revival',
      'Eric Clapton',
      'Cream',
      'The Yardbirds',
      'Faces',
      'Neil Young',
      'Ron Wood',
      'Paul McCartney',
      'Derek and the Dominos',
      'The Animals',
      'The Jimi Hendrix Experience',
      'The Byrds',
      'George Harrison',
      'Queen',
      'Aerosmith',
      'Viet Cong',
      'Ought',
      'Protomartyr',
      'Iceage',
      'No Age',
      'Shame',
      'Idles',
      'Shopping',
      'The Men',
      'METZ',
      'Girl Band',
      'Algiers',
      'Eagulls',
      'Liars',
      'Hot Snakes',
      'Priests',
      'Savages',
      'Flasher',
      'Marching Church',
      'Total Control',
      'Exploded View',
      'Gang of Four',
      "Melody's Echo Chamber",
      'Unknown Mortal Orchestra',
      'MGMT',
      'King Gizzard & The Lizard Wizard',
      'The Holydrug Couple',
      'The Strokes',
      'Boogarins',
      'Arctic Monkeys',
      'Foxygen',
      'Dungen',
      'Mild High Club',
      'Grizzly Bear',
      'The Flaming Lips',
      'Jagwar Ma',
      'Moses Gunn Collective',
      'Interpol',
      'Morgan Delt',
      'Foals',
      'Neon Indian',
      'Pink Floyd',
      'Arcade Fire',
      'Tin Machine',
      'Lou Reed',
      'Iggy Pop',
      'T. Rex',
      'Roxy Music',
      'The Velvet Underground',
      'Queen & David Bowie',
      'Talking Heads',
      'Brian Eno',
      'Bryan Ferry',
      'Nick Cave & The Bad Seeds',
      'Mott the Hoople',
      'Blondie',
      'Kate Bush',
      'Sparks',
      'Dead Ghosts',
      'Froth',
      'The Mystery Lights',
      'Meatbodies',
      'The Murlocs',
      'White Fence',
      'Levitation Room',
      'Cosmonauts',
      'Jacuzzi Boys',
      'Black Lips',
      'The Shivas',
      'King Tuff',
      'together PANGEA',
      'Tijuana Panthers',
      'Bleached',
      'Vivian Girls',
      'Harlem',
      'Audacity',
      'La Sera',
      'Mikal Cronin',
      'Woods',
      'The Growlers',
      'The Orwells',
      'The Strange Boys',
      'Twin Peaks',
      'The King Khan & BBQ Show',
      'Shannon and the Clams',
      'White Reaper',
      'The Beets',
      'Surf Curse',
      'Smith Westerns',
      'Tomorrows Tulips',
      'Föllakzoid',
      'The Black Ryder',
      'White Hills',
      'Kikagaku Moyo',
      'The Telescopes',
      'Spiritualized',
      'The Jesus and Mary Chain',
      'Ride',
      'The Morning After Girls',
      'Damaged Bug',
      'Wand',
      'Ty Segall Band',
      'Coachwhips',
      'Ty Segall & White Fence',
      'Ty Segall & Mikal Cronin',
      'Jay Reatard',
      'Gliss',
      'Darker My Love',
      'The Third Sound',
      'Skywave',
      'Ringo Deathstarr',
      'Ceremony',
      'Crystal Stilts',
      'Nothing',
      'Odonis Odonis',
      'Have a Nice Life',
      'The Raveonettes',
      'Pinkshinyultrablast',
      'DIIV',
      'Swervedriver',
      'Disappears',
      'Spindrift',
      'Stone Dead',
      '10000 Russos',
      'Las Cobras',
      'Black Bombaim',
      'Killimanjaro',
      'Kungens Män',
      'Mt. Mountain',
      'Dead Sea Apes',
      'Anthroprophh',
      'Quelle Dead Gazelle',
      'Keep Razors Sharp',
      'Ganso',
      'Dead Gurus',
      'Blown Out',
      'HOLY NOTHING',
      'Cave Story',
      'Vuelveteloca',
      'The Glockenwise',
      'Electric Eye',
      'Hills',
      'The Moonlandingz',
      'Mr. Elevator & The Brain Hotel',
      'GØGGS',
      'Uncle Acid & the Deadbeats',
      'Band of Skulls',
      '22-20s',
      'The Kills',
      'The Vines',
      'The Dead Weather',
      'The Raconteurs',
      'Blood Red Shoes',
      'The White Stripes',
      'Eagles of Death Metal',
      'TheBlack Keys',
      'The Duke Spirit',
      'Franz Ferdinand',
      'Editors',
      'Queens of the Stone Age',
      'Royal Blood',
      'The Music',
      'The Subways',
      'Jack White',
      'Os Capitães da Areia',
      'Peixe : Avião',
      'The Happy Mess',
      'Sean Riley & The Slowriders',
      'Galgo',
      'Flying Cages',
      'Indignu',
      'Capicua',
      'Filipe Sambado',
      'PZ',
      'The Lazy Faithful',
      'Tomara',
      'For Pete Sake',
      'Virgem Suta',
      'Imploding Stars',
      'Miguel Araújo',
      'Them Flying Monkeys',
      'Throes + The Shine',
      'Stephen Malkmus and the Jicks',
      'Pavement',
      'Father John Misty',
      'Wire',
      'Mitski',
      'Hop Along',
      'Teenage Cool Kids',
      'Mission of Burma',
      'White Denim',
      'Omni',
      'Built to Spill',
      'Holygram',
      'Second Still',
      'A Projection',
      'The Agnes Circle',
      'Box And The Twins',
      'Then Comes Silence',
      'All Your Sisters',
      'Winter Severity Index',
      'Double Echo',
      'Horror Vacui',
      'The Foreign Resort',
      'Traitrs',
      'Red Lorry Yellow Lorry',
      'Skeleton Hands',
      'FOREVER GREY',
      'Pink Turns Blue',
      'The Proper Ornaments',
      'Ultimate Painting',
      'Hookworms',
      'Flat Worms',
      'Chastity Belt',
      'Quilt',
      'Beak>',
      'Doug Tuttle',
      'Triptides',
      'Klaxons',
      'Hot Chip',
      'Late of the Pier',
      'Thieves Like Us',
      'Friendly Fires',
      'Is Tropical',
      'Caribou',
      'Phoenix',
      'The Shoes',
      'Midnight Juggernauts',
      'New Young Pony Club',
      'Does It Offend You, Yeah?',
      'Django Django',
      'LCD Soundsystem',
      'Cut Copy',
      'Cansei de Ser Sexy',
      'Digitalism',
      'Crystal Castles',
      'The Whitest Boy Alive',
      '!!!',
      'Justice',
      'Totally Enormous Extinct Dinosaurs',
      'The Hives',
      'The Datsuns',
      'The Greenhornes',
      'Dirty Pretty Things',
      'Louis XIV',
      'The Rakes',
      'The Mooney Suzuki',
      'Black Pistol Fire',
      'Nine Black Alps',
      'The Detroit Cobras',
      'The Futureheads',
      'The Bravery',
      'Hot Hot Heat',
      'Archie Bronson Outfit',
      'The Pigeon Detectives',
      'The Vaccines',
      'The Libertines',
      'Blossoms',
      'The Courteeners',
      'Peace',
      'The Kooks',
      'The Rascals',
      'Alex Turner',
      'Babyshambles',
      'Beady Eye',
      'The Fratellis',
      'Johnny Marr',
      'Eugene McGuinness',
      "Noel Gallagher's High Flying Birds",
      'Jamie T',
      'Mini Mansions',
      'The Coral',
      'Kaiser Chiefs',
      'The Wombats',
      'Circa Waves',
      'Morrissey',
      'Joy Division',
      'New Order',
      'The Cure',
      'Echo & the Bunnymen',
      'Siouxsie and the Banshees',
      'The Stone Roses',
      'Pulp',
      'Suede',
      'Tears for Fears',
      'The Chameleons',
      'The Psychedelic Furs',
      'Mac DeMarco',
      'Blur',
      'Public Image Ltd.',
      'The Sound',
      'Sonic Youth',
      'Television',
      'Go Back to the Zoo',
      'The Mysterons',
      'Birth of Joy',
      'DeWolff',
      'Black Honey',
      'Klangstof',
      'Amber Arcades',
      'Kensington',
      'Pip Blom',
      'Bartek',
      'Navarone',
      'ZZZ',
      'korfbal',
      'Claw Boys Claw',
      'Moke',
      'Iguana Death Cult',
      'Balthazar',
      'CUT_',
      'Psychedelic Porn Crumpets',
      'Jacco Gardner',
      'Otherkin',
      'The Wytches',
      'Wavves',
      'Fidlar',
      'Nobunny',
      'My Bloody Valentine',
      'Mojave 3',
      'Cocteau Twins',
      'DropNineteens',
      'Lush',
      'Galaxie 500',
      'Chapterhouse',
      'Pale Saints',
      'Beach House',
      'Airiel',
      'Secret Shine',
      'Mazzy Star',
      'LSD and the Search for God',
      'Whirr',
      'Cranes',
      'Grouper',
      'Tamaryn',
      'Deerhunter',
      'lovesliescrushing',
      'Motorama',
      'Belgrado',
      'Утро',
      'Manicure',
      'PLOHO',
      'Be Forest',
      'Holograms',
      'Sad Lovers and Giants',
      'Virtual Haze',
      'cascabel',
      'The Mud Howlers',
      'San Pedro el cortez',
      'The Risin Sun',
      'Slim Forsythe',
      'Felipe El Hombre',
      'Los Mundos',
      'Vaya Futuro',
      'The Wookies',
      'Policias y Ladrones',
      "The Maggie's Marshmallows",
      'the baron four',
      'Sadfields',
      'Los Pepes',
      'Los Explosivos',
      'Prietto viaja al cosmos con Mariano',
      '60 Tigres',
      'Click (Rocio Sobrado Ramirez)',
      'El Shirota',
      'O Tortuga',
      'Norwayy',
      'Le Baron',
      'Cool Ghouls',
      'The Babe Rainbow (aus)',
      'Guantanamo Baywatch',
      'Bob Dylan and The Band',
      'The Band',
      'Leonard Cohen',
      'Van Morrison',
      'Woody Guthrie',
      'Bruce Springsteen',
      'Neil Young & Crazy Horse',
      'Tom Waits',
      'Joan Baez',
      'Paul Simon',
      'Simon & Garfunkel',
      'Crosby, Stills, Nash & Young',
      'Donovan',
      'The Beach Boys',
      'Joni Mitchell',
      'Bruce Springsteen & The E Street Band',
      'Buffalo Springfield',
      'Cat Stevens',
      'Catfish and The Bottlemen',
      'Cage the Elephant',
      'Peter Doherty',
      'Miles Kane and the Death Ramps',
      'Albert Hammond, Jr.',
      'Julian Casablancas',
      'Two Door Cinema Club',
      'Mando Diao',
      'Sugarplum Fairy',
      'Friska Viljor',
      'Moneybrother',
      'Kent',
      'Shout Out Louds',
      'Caesars',
      'Kraftklub',
      'Maxïmo Park',
      'Royal Republic',
      'Broder Daniel',
      'Tiger Lou',
      'Bilderbuch',
      'Kettcar',
      'Kilians',
      'Madsen',
      'Thees Uhlmann',
      'Slut',
      'Tomte',
      'Håkan Hellström',
      'The Sounds',
      'Timo Räisänen',
      'Oasis',
      'Muse',
      'Hard-Fi',
      'The Killers',
      'Acid Baby Jesus',
      'Bleeding Knees Club',
      'Skaters',
      'Splashh',
    ],
  },
  name: 'lastfm_gereeet',
  __v: 6,
};
